### ISSUE TITLE
Bannerize does not handle SASS generated BOM char

### ISSUE THREAD

**Issue by hartman** [misteroneill/bannerize#3]
SASS outputs a BOM (\ufeff) character at the start of the generated files. Bannerize does not take this into account and just puts bytes in front of the BOM char. You then have a BOM char in the middle of the file, which is an invalid CSS file, that is ignored by (some? at least Chrome) browsers.

**Comment by misteroneill** [comment]
@hartman Sorry it took me so long to get around to this - it got lost in the shuffle among a bunch of other things. I just published v1.1.1 which should fix this issue.

**Comment by hartman** [comment]
Thanks !
