### ISSUE TITLE
bannerize adds LF at the end of a banner even when linebreak is set as CRLF

### ISSUE THREAD

**Issue by CxRes** [misteroneill/bannerize#6]
Like the title says. I have ensured that there is `CRLF` at the end of `banner.ejs` before the `EOF`. Even then it gets replaced by `LF`
bannerize v1.1.2, nodejs v8.1.4, Windows 10 x64

**Comment by CxRes** [comment]
I think the issue is that internally you call the `lineBreak` option as `lineBreaks`

**Comment by misteroneill** [comment]
Thanks for the report @CxRes - seems like there was a mis-match between the documentation and the code. It should be fixed now (v1.1.3) with both `lineBreak` and `lineBreaks` options supported!
