### ISSUE TITLE
Add api example

### ISSUE THREAD

**Issue by thijstriemstra** [misteroneill/bannerize#7]
For some reason this doesn't add a banner. It's run using `npm run foo` and `foo` does `node path-to-file.js` with the following contents:

```javascript
var bannerize = require('bannerize');
var fs = require('fs');
var path = require('path');

var pluginDestPath = 'dist-test/plugins/videojs.record.libvorbis.js';
bannerize(pluginDestPath, {
    banner: 'scripts/banner.ejs',
    cwd: path.join(__dirname, '..')
}).then(function () {
    console.log('Added banner to ' + pluginDestPath);
});
```

Content of banner.ejs:
```javascript
/**
 * <%- pkg.name %>
 * @version <%- pkg.version %>
 * @see <%- pkg.homepage %>
 * @copyright 2014-<%- date.getFullYear() %> <%- pkg.author %>
 * @license <%- pkg.license %>
 */

```

What am I missing here?

Can you add an API example to the readme that demonstrates node usage?

**Comment by misteroneill** [comment]
I'll check it out, thanks!

**Comment by misteroneill** [comment]
@thijstriemstra Does #8 seem good to you?

Also, I'm not sure what your precise project structure is. I set something up similar to this and it worked fine. You might make sure your `pluginDestPath` and `banner` option path are both correct relative to the `cwd` you're providing.
